# Renders docs/vim.md from the nixvim configuration.
# Build with `nix build .#vim-docs`, or regenerate the checked-in file
# with `nix run .#vim-docs`.
{
  pkgs,
  lib,
}: let
  cfg = (import ../modules/home-manager/base/vim.nix {inherit pkgs;}).programs.nixvim;

  esc = s: lib.replaceStrings ["|" "\n"] ["\\|" " "] s;
  code = s:
    if s == ""
    then ""
    else "`${esc s}`";

  table = headers: rows:
    lib.concatStringsSep "\n" (
      [
        "| ${lib.concatStringsSep " | " headers} |"
        "| ${lib.concatStringsSep " | " (map (_: "---") headers)} |"
      ]
      ++ map (row: "| ${lib.concatStringsSep " | " row} |") rows
    );

  modeNames = {
    n = "normal";
    i = "insert";
    v = "visual";
    x = "visual";
    t = "terminal";
  };
  modeStr = m: let
    ms =
      if builtins.isList m
      then m
      else [m];
  in
    lib.concatStringsSep ", " (map (x: modeNames.${x} or x) ms);

  # --------------------------------------------------------------------------
  # Keymaps declared in `keymaps`
  # --------------------------------------------------------------------------
  keymapRows =
    map (
      k: [
        (code k.key)
        (modeStr (k.mode or "n"))
        (esc (k.options.desc or ""))
        (
          if builtins.isString k.action
          then code k.action
          else "*(lua)*"
        )
      ]
    )
    cfg.keymaps;

  # --------------------------------------------------------------------------
  # Keymaps buried in raw Lua (extraConfigLua, gitsigns on_attach).
  # Best-effort: scans for `vim.keymap.set("<mode>", "<key>", ...)` and
  # `map("<mode>", "<key>", ...)` calls and pulls out the desc.
  # --------------------------------------------------------------------------
  extractLuaKeymaps = lua: let
    parts = builtins.split ''(vim\.keymap\.set|map)\('' lua;
    chunks = lib.filter builtins.isString (lib.tail parts);
    parse = chunk: let
      m = builtins.match ''[[:space:]]*"([a-zA-Z]+)",[[:space:]]*"([^"]*)".*'' chunk;
      d = builtins.match ''.*desc = "([^"]*)".*'' chunk;
    in
      if m == null
      then null
      else {
        mode = lib.head m;
        key = lib.elemAt m 1;
        desc =
          if d == null
          then ""
          else lib.head d;
      };
  in
    lib.filter (x: x != null) (map parse chunks);

  luaKeymapRows = src:
    map (k: [(code k.key) (modeStr k.mode) (esc k.desc)]) (extractLuaKeymaps src);

  # --------------------------------------------------------------------------
  # Plugin-owned keymaps
  # --------------------------------------------------------------------------
  telescopeRows =
    lib.mapAttrsToList (
      key: v: [(code key) (code v.action) (esc (v.options.desc or ""))]
    )
    cfg.plugins.telescope.keymaps;

  lspRows =
    lib.mapAttrsToList (
      key: v: [(code key) (code v.action) (esc (v.desc or ""))]
    )
    cfg.plugins.lsp.keymaps.lspBuf;

  whichKeyRows =
    map (
      s: [(code s.__unkeyed-1) (esc s.group)]
    )
    cfg.plugins.which-key.settings.spec;

  # --------------------------------------------------------------------------
  # Plugins / LSP / tooling
  # --------------------------------------------------------------------------
  enabledPlugins = lib.sort lib.lessThan (lib.attrNames (
    lib.filterAttrs (_: v: builtins.isAttrs v && (v.enable or false)) cfg.plugins
  ));

  lspServers = lib.sort lib.lessThan (lib.attrNames (
    lib.filterAttrs (_: v: v.enable or false) cfg.plugins.lsp.servers
  ));

  ftToolRows = attrs:
    lib.mapAttrsToList (
      ft: tools: [(code ft) (lib.concatStringsSep ", " (map code tools))]
    )
    attrs;

  grammars = lib.sort lib.lessThan (
    map (g: lib.removePrefix "tree-sitter-" (lib.getName g))
    cfg.plugins.treesitter.grammarPackages
  );

  extraPackages = lib.sort lib.lessThan (map lib.getName cfg.extraPackages);

  optValue = v:
    if builtins.isBool v
    then code (lib.boolToString v)
    else if builtins.isAttrs v || builtins.isList v
    then code (builtins.toJSON v)
    else code (toString v);

  optRows = lib.mapAttrsToList (name: v: [(code name) (optValue v)]) cfg.opts;

  autoCmdRows =
    map (
      a: [
        (lib.concatStringsSep ", " (map code (lib.toList a.event)))
        (code (a.group or ""))
        (esc (a.desc or ""))
      ]
    )
    cfg.autoCmd;

  markdown = ''
    <!-- Generated by `nix run .#vim-docs` from modules/home-manager/base/vim.nix — do not edit by hand. -->

    # Neovim configuration

    Declarative [nixvim](https://github.com/nix-community/nixvim) setup.
    Leader key: `${
      if cfg.globals.mapleader == " "
      then "<Space>"
      else cfg.globals.mapleader
    }` · Colorscheme: `tokyonight` (${cfg.colorschemes.tokyonight.settings.style})

    ## Keymaps

    ${table ["Key" "Mode" "Description" "Action"] keymapRows}

    ### Key groups (which-key)

    ${table ["Prefix" "Group"] whichKeyRows}

    ### Telescope

    ${table ["Key" "Picker" "Description"] telescopeRows}

    ### LSP

    ${table ["Key" "Action" "Description"] lspRows}

    ### Git hunks (buffer-local, via gitsigns)

    ${table ["Key" "Mode" "Description"] (luaKeymapRows cfg.plugins.gitsigns.settings.on_attach.__raw)}

    ### Extra keymaps (defined in Lua)

    ${table ["Key" "Mode" "Description"] (luaKeymapRows cfg.extraConfigLua)}

    ## Plugins

    ${lib.concatMapStringsSep "\n" (p: "- `${p}`") enabledPlugins}

    ## Language support

    ### LSP servers

    ${lib.concatMapStringsSep "\n" (s: "- `${s}`") lspServers}

    ### Formatters (conform-nvim)

    ${table ["Filetype" "Formatters"] (ftToolRows cfg.plugins.conform-nvim.settings.formatters_by_ft)}

    ### Linters (nvim-lint)

    ${table ["Filetype" "Linters"] (ftToolRows cfg.plugins.lint.lintersByFt)}

    ### Treesitter grammars

    ${lib.concatStringsSep ", " (map (g: "`${g}`") grammars)}

    ## Options

    ${table ["Option" "Value"] optRows}

    ## Autocommands

    ${table ["Event(s)" "Group" "Description"] autoCmdRows}

    ## Extra packages

    ${lib.concatStringsSep ", " (map (p: "`${p}`") extraPackages)}
  '';
in
  pkgs.writeText "vim.md" markdown
