# Shared markdown rendering helpers for the docs generators.
{lib}: rec {
  banner = src: "<!-- Generated by `nix run .#docs` from ${src} — do not edit by hand. -->";

  esc = s: lib.replaceStrings ["|" "\n"] ["\\|" " "] s;

  code = s:
    if s == ""
    then ""
    else if lib.hasInfix "`" s
    then "`` ${esc s} ``"
    else "`${esc s}`";

  codeList = xs: lib.concatStringsSep ", " (map code xs);

  link = text: url: "[${text}](${url})";

  # Package name linked to its upstream homepage, when nixpkgs knows one.
  pkgLink = p: let
    name = code (lib.getName p);
    homepage = p.meta.homepage or null;
  in
    if homepage == null
    then name
    else link name homepage;

  pkgLinkList = ps: lib.concatStringsSep ", " (map pkgLink (lib.sort (a: b: lib.getName a < lib.getName b) ps));

  bullets = xs: lib.concatMapStringsSep "\n" (x: "- ${x}") xs;

  table = headers: rows:
    lib.concatStringsSep "\n" (
      [
        "| ${lib.concatStringsSep " | " headers} |"
        "| ${lib.concatStringsSep " | " (map (_: "---") headers)} |"
      ]
      ++ map (row: "| ${lib.concatStringsSep " | " row} |") rows
    );

  value = v:
    if builtins.isBool v
    then lib.boolToString v
    else if builtins.isAttrs v || builtins.isList v
    then builtins.toJSON v
    else toString v;
}
